---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3166390407-SGrRix4ph6IYEfPIcrWkfkyAEQpUGdlqyi86pkg
:access_token_secret: PkhlBGIZ7dQRB1wcveuQiYqFAILDHuBFHIubiKPaQewIN
